name: CI/CD Deploy to WSL

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]   # depends on docker.yml
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to WSL2 server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull joshuachigozie26/devops-demo-app:latest

            echo "Stopping old container (if exists)..."
            docker stop myapp || true
            docker rm myapp || true

            echo "Starting new container..."
            docker run -d --name myapp -p 3000:3000 joshuachigozie26/devops-demo-app:latest
